task:
    windows_container:
      image: cirrusci/windowsservercore:2019
    env:
      - CIRRUS_SHELL: powershell
      - GITHUB_TOKEN: ENCRYPTED[4c0cfca7f925a125575a0da63c0781ddc5871e35c8af9c54c67837bc612a3f763c6fda1b39224c36f6bce162c9ad1c58]
    setup_script:
    - choco install -y --no-progress dotnet-sdk --pre
    - refreshenv
    - $env:Path = [System.Environment]::GetEnvironmentVariable("Path","Machine") + ";" + [System.Environment]::GetEnvironmentVariable("Path","User") 
    script:
    - $env:Path = [System.Environment]::GetEnvironmentVariable("Path","Machine") + ";" + [System.Environment]::GetEnvironmentVariable("Path","User") 
    - certutil -user -p jukatest -importPFX Juka.pfx NoRoot
    - dotnet workload restore JukaApp.csproj --ignore-failed-sources
    compile_script:
    - $env:Path = [System.Environment]::GetEnvironmentVariable("Path","Machine") + ";" + [System.Environment]::GetEnvironmentVariable("Path","User") 
    - dotnet workload restore JukaApp.csproj --ignore-failed-sources
    - dotnet restore JukaApp.csproj --ignore-failed-sources
    - $mypwd = ConvertTo-SecureString -String "jukatest" -Force -AsPlainText
    - $Thumbprint = (Get-PfxData -Password $mypwd -FilePath "./Juka.pfx").EndEntityCertificates.Thumbprint
    - dotnet publish JukaApp.csproj -f net6.0-windows10.0.19041.0 -c Debug /p:PackageCertificateThumbprint="$Thumbprint" /p:PackageCertificateKeyFile="Juka.cer" /p:AppxPackageSigningEnabled=true
    upload_script:
    - $CIRRUS_RELEASE = (Invoke-WebRequest  -UseBasicParsing -Uri "https://api.github.com/repos/JukaLang/juka/releases/latest" | ConvertFrom-Json).tag_name
    - $headers = @{Authorization="token $env:MYTOKEN"}
    - $postparam = (@{"tag_name" = $CIRRUS_RELEASE; "target_commitish" = "master"; "name" = $CIRRUS_RELEASE; "body"="Juka App released on "+$CIRRUS_RELEASE; "draft"=$false;"prerelease"=$false;"generate_release_notes"=$false} |ConvertTo-Json)
    - $output = (Invoke-WebRequest -URI https://api.github.com/repos/jukalang/jukaapp/releases -Method POST -Body $postparam -Headers $headers -ContentType "application/octet-stream" -UseBasicParsing)
    - $releaseID = ($output | ConvertFrom-Json).id
    - Invoke-WebRequest -URI https://uploads.github.com/repos/jukalang/jukaapp/releases/$releaseID/assets?name=JukaApp.msix -Method POST -InFile "C:\Users\ContainerAdministrator\AppData\Local\Temp\cirrus-ci-build\bin\Debug\net6.0-windows10.0.19041.0\win10-x64\AppPackages\JukaApp_1.0.0.1_Debug_Test\JukaApp_1.0.0.1_x64_Debug.msix"  -ContentType "application/octet-stream" -Headers $headers -UseBasicParsing
    - dir